### PR TITLE
(#4) Replace `Newtonsoft.Json` with `System.Text.Json`

### LINKED ISSUE #4: Replace `Newtonsoft.Json` with `System.Text.Json`
To become 100% free of third-party libraries at runtime.

### PR DESCRIPTION
**Pull request by y0ung3r**
Should close #4 

The `PolymorphicTypeResolver` class was added to (de)serialize abstract classes and interfaces (but it doesn't support generic types for inheritors).

I suppose I could have broken something or missed something. But I think it will help a lot in solving the problem.

### CODE REVIEW

**Comment by seclerp** [comment]
Hi @y0ung3r, thanks for the contribution! I need some time to test it a bit. Overall it looks good to me

**Comment by seclerp** [comment]
Hi @y0ung3r, I have introduced 2 more JsonConverters ([`ObjectTypeConverter`](https://github.com/seclerp/dotnet-chrome-protocol/blob/v1.3.0/src/ChromeProtocol.Core/ObjectTypeConverter.cs) and [`ArrayTypeConverter`](https://github.com/seclerp/dotnet-chrome-protocol/blob/v1.3.0/src/ChromeProtocol.Core/ArrayTypeConverter.cs)) to fix the issue #7, could you please migrate them as well?

**Comment by seclerp** [comment]
Please let me know if you need some sort of test project

**Comment by y0ung3r** [comment]
Hi @seclerp

> I have introduced 2 more JsonConverters ([ObjectTypeConverter](https://github.com/seclerp/dotnet-chrome-protocol/blob/v1.3.0/src/ChromeProtocol.Core/ObjectTypeConverter.cs) and [ArrayTypeConverter](https://github.com/seclerp/dotnet-chrome-protocol/blob/v1.3.0/src/ChromeProtocol.Core/ArrayTypeConverter.cs)) to fix the issue https://github.com/seclerp/dotnet-chrome-protocol/issues/7, could you please migrate them as well?

I'll do it when I have some free time

> Please let me know if you need some sort of test project

Okay, thank you!

**Comment by y0ung3r** [comment]
Hi @seclerp!

It's done! 
In addition, I added tests to check that `ArrayTypeConverter` and `ObjectTypeConverter` work properly

**Comment by seclerp** [comment]
Apologies for the long delay with the review. LGTM, will merge it today, thank you one more time!

**Review by seclerp — APPROVED** [review]

**Comment by NCLnclNCL** [comment]
Any plans to make it compatible with native aot?

**Comment by NCLnclNCL** [comment]
> Apologies for the long delay with the review. LGTM, will merge it today, thank you one more time!


Any plans to make it compatible with native aot?

**Pull request merged**
